# Dockerfile for Python backend with minimal Alpine base
FROM python:3.12-alpine

# Maintainer information
LABEL maintainer="jerry"
WORKDIR /home

# Install only essential packages
RUN apk add --no-cache \
        git \
        supervisor

# Clone backend code
RUN git clone https://github.com/liuyal/project_orbit.git orbit
ENV PYTHONPATH=/home/orbit
ENV MONGODB_HOST=db-app

# Set up Python environment
RUN pip install --no-cache-dir -r /home/orbit/poetry-env/requirements.txt

# Configure Supervisor to manage container services
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
