DavLockDB /usr/local/apache2/var/DavLock

<Location /files>
    DAV On
    Require all granted

    <LimitExcept GET PUT MKCOL>
        Require all denied
    </LimitExcept>
</Location>

<Directory "/usr/local/apache2/htdocs/files">
    DAV On
    Require all granted
</Directory>