DavLockDB /usr/local/apache2/var/DavLock

<Location /files>
    DAV On
    Options Indexes

    Require all granted

    <LimitExcept GET PUT MKCOL DELETE PROPFIND PROPPATCH COPY MOVE OPTIONS LOCK UNLOCK HEAD>
        Require all denied
    </LimitExcept>
</Location>

<Directory "/usr/local/apache2/htdocs/files">
    DAV On
    Options Indexes
    AllowOverride None
    Require all granted
</Directory>